Downgrade StackExchange.Redis to 1.2.4
bonesoul/CoiniumServ pull request #1000
Opened 2018-03-23 11:14 UTC by jeong760

2018-03-24 19:33 UTC, bonesoul requested changes
@jeong760 please don't upgrade mysqldata and let it stay with 6.8.8.

reason; https://github.com/fluentmigrator/fluentmigrator/issues/821

6.9.10 seems good enough.

2018-03-24 19:33 UTC, bonesoul commented on src/CoiniumServ/packages.config
> -  <package id="MySql.Data" version="6.8.8" targetFramework="net47" />
this change may cause bugs actually, as we are strictly staying on mysql.data 6.8.8

can you confirm that everything is okay with 6.9.11?

2018-03-24 19:33 UTC, bonesoul commented on src/CoiniumServ/packages.config
> -  <package id="MySql.Data" version="6.8.8" targetFramework="net47" />
we should use 6.9.10 or 6.8.8

2018-03-24 22:28 UTC, jeong760 commented
@Bonesoul,

Ok, I will made a change this to MySql 6.9.10.

Regards,
John Ahn
-----Original Message-----
From: "Hüseyin Uslu"<notifications@github.com>
To: "bonesoul/CoiniumServ"<CoiniumServ@noreply.github.com>;
Cc: "John Ahn"<jeong760@naver.com>; "Mention"<mention@noreply.github.com>;
Sent: 2018-03-25 (일) 04:33:49
Subject: Re: [bonesoul/CoiniumServ] Downgrade StackExchange.Redis to 1.2.4 (#1000)

@bonesoul commented on this pull request.
In src/CoiniumServ/packages.config:
> @@ -11,7 +11,7 @@ <package id="JsonConfig" version="1.0.0" targetFramework="net47" /> <package id="JsonFx" version="2.0.1209.2802" targetFramework="net47" /> <package id="Microsoft.AspNet.Razor" version="3.2.4" targetFramework="net47" /> - <package id="MySql.Data" version="6.8.8" targetFramework="net47" />
we should use 6.9.10 or 6.8.8
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

2018-03-27 16:38 UTC, HashUnlimited commented
For the sake of traceability, can the PR be split into fixes and additions?

2018-03-27 21:20 UTC, bonesoul commented
I count with that @HashUnlimited

2018-03-28 02:23 UTC, closed without merging